import fs from "fs";

import { TreeNode } from "../utils";
import parse from "./parse";

/**
 * This is the compile function, this function will compile the source code given in the 3rd argument.
 * @note This function has no arguments.
 */

const compile = (): void => {
  const ast: Array<TreeNode> = parse(process.argv[2]);

  fs.writeFileSync(
    "./out.chat",
    `This file is automatically generated, DO NOT EDIT DIRECTLY!! \n${Buffer.from(
      JSON.stringify(ast)
    ).toString("base64")}`
  );
};

export default compile;

compile();
