import compile from "./compiler/compile";
import run from "./runner/run";
import readFile from "./utils/readFile";

if (process.argv[process.argv.length - 2] === "compile") {
  compile();
}

if (process.argv[process.argv.length - 2] === "run") {
  const ast: string = String(readFile(process.argv[process.argv.length - 1])).replace(
    "This file is automatically generated, DO NOT EDIT DIRECTLY!! \n",
    ""
  );

  run(ast);
}
