import compile from "./compiler/compile";
import run from "./runner/run";
import readFile from "./utils/readFile";

if (process.argv[3] === "compile") {
  compile();
}

if (process.argv[3] === "run") {
  const ast: string = String(readFile(process.argv[2])).replace(
    "This file is automatically generated, DO NOT EDIT DIRECTLY!! \n",
    ""
  );

  run(ast);
}
